name: Update Random Image
on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pick random image and update README
        run: |
          IMAGES=(
            "https://raw.githubusercontent.com/archpup/images/main/Untitled119_20251023194142.png"
            "https://raw.githubusercontent.com/archpup/images/main/Untit
