name: Update Random Image
on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:       # allow manual run

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pick random image and update README
        run: |
          IMAGE=$(ls images | shuf -n 1)
          echo "Selected image: $IMAGE"
          sed -i "s|!\[Random Image\](.*)|![Random Image](https://raw.githubusercontent.com/${{ github.repository }}/main/images/${IMAGE})|" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update random image: $(date)"
          git push
          
